name: Multi-Cloud Enterprise CI/CD Pipeline

on:
  workflow_call:
    inputs:
      cloud:
        required: true
        type: string

      java_dir:
        required: false
        type: string

      python_dir:
        required: false
        type: string

      node_dir:
        required: false
        type: string

      image_name:
        required: false
        type: string

permissions:
  id-token: write
  contents: read
  

# ==========================================================
# =================  BUILD & UNIT TEST ==================
# ==========================================================

jobs:

  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ---------------- JAVA ----------------
      - name: Setup Java
        if: ${{ hashFiles(format('{0}/pom.xml', env.JAVA_DIR)) != '' }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Java Build & Test
        if: ${{ hashFiles(format('{0}/pom.xml', env.JAVA_DIR)) != '' }}
        run: |
          cd $JAVA_DIR
          mvn clean verify

      # ---------------- PYTHON ----------------
      - name: Setup Python
        if: ${{ hashFiles(format('{0}/requirements.txt', env.PYTHON_DIR)) != '' }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Python Test
        if: ${{ hashFiles(format('{0}/requirements.txt', env.PYTHON_DIR)) != '' }}
        run: |
          cd $PYTHON_DIR
          pip install -r requirements.txt
          pip install pytest
          pytest

      # ---------------- NODE ----------------
      - name: Setup Node
        if: ${{ hashFiles(format('{0}/package.json', env.NODE_DIR)) != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Node Test
        if: ${{ hashFiles(format('{0}/package.json', env.NODE_DIR)) != '' }}
        run: |
          cd $NODE_DIR
          npm install
          npm test -- --watchAll=false

# ==========================================================
# =================  UPLOAD ARTIFACT =======================
# ==========================================================

 
  upload-artifact:
    runs-on: ubuntu-latest
    # needs: build-test
  
    steps:
      - uses: actions/checkout@v4
  
      # ---------------- AWS LOGIN ----------------
      - name: Configure AWS Credentials
        if: github.event.inputs.cloud == 'aws'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::088310115913:role/OpenID-Connect
          aws-region: us-east-1
  
      # ---------------- Upload Full Repo ----------------
      - name: Upload Full Repo
        uses: actions/upload-artifact@v4
        with:
          name: artifact-file
          path: artifact-file
            **/*
            !node_modules/**
            !__pycache__/**
            !image.tar
  
      # ---------------- Setup Java ----------------
      - name: Deploy Java to CodeArtifact
        run: |
          cd java_springboot
      
          VERSION=0.0.${{ github.run_number }}
      
          CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token \
            --domain my-domain \
            --domain-owner 088310115913 \
            --query authorizationToken \
            --output text \
            --region us-east-1)
      
          mkdir -p ~/.m2
      
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>my-domain-my-repo</id>
                <username>aws</username>
                <password>${CODEARTIFACT_AUTH_TOKEN}</password>
              </server>
            </servers>
          </settings>
          EOF
      
          # SET DYNAMIC VERSION
          mvn versions:set -DnewVersion=$VERSION
      
          # BUILD & DEPLOY
          mvn clean deploy \
            -DaltDeploymentRepository=my-domain-my-repo::default::https://my-domain-088310115913.d.codeartifact.us-east-1.amazonaws.com/maven/my-repo/ \
            -DskipTests
            
      # ---------------- Setup Python ----------------
      - name: Setup Python
        if: hashFiles('python_app/requirements.txt') != ''
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
  
      # ---------------- Push Python to CodeArtifact ----------------
      - name: Deploy Python to CodeArtifact
        if: github.event.inputs.cloud == 'aws' && hashFiles('python_app/requirements.txt') != ''
        run: |
          cd python_app
          pip install build twine
          python -m build
  
          aws codeartifact login \
            --tool twine \
            --domain my-domain \
            --domain-owner 088310115913 \
            --repository my-repo \
            --region us-east-1
  
          twine upload dist/*
  
      # ---------------- Setup Node ----------------
      - name: Setup Node
        if: hashFiles('react_node_app/package.json') != ''
        uses: actions/setup-node@v4
        with:
          node-version: '18'
  
      # ---------------- Push Node to CodeArtifact ----------------
      - name: Deploy Node to CodeArtifact
        if: github.event.inputs.cloud == 'aws' && hashFiles('react_node_app/package.json') != ''
        run: |
          cd react_node_app
  
          aws codeartifact login \
            --tool npm \
            --domain my-domain \
            --domain-owner 088310115913 \
            --repository my-repo \
            --region us-east-1
  
          npm publish
  
      # ---------------- Push Full Repo Artifact to GCP Artifact Registry ----------------
      - name: Authenticate to GCP
        if: github.event.inputs.cloud == 'gcp'
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      
      - name: Setup GCloud SDK
        if: github.event.inputs.cloud == 'gcp'
        uses: google-github-actions/setup-gcloud@v2
      
      - name: Push Full Repo Artifact to GCP Artifact Registry
        if: github.event.inputs.cloud == 'gcp'
        run: |
          zip -r full-repo.zip .
      
          gcloud artifacts generic upload \
            --location=us-central1 \
            --repository=my-repo \
            --package=full-repo \
            --version=$VERSION \
            --source=full-repo.zip
        
      # ---------------- Push Full Repo Artifact to Azure ----------------
      - name: Push Full Repo Artifact to Azure Artifacts
        if: github.event.inputs.cloud == 'azure'
        run: |
          cd artifact-file
          zip -r full-repo.zip *
          
          az artifacts universal publish \
            --organization https://dev.azure.com/my-org \
            --feed my-feed \
            --name full-repo \
            --version $VERSION \
            --description "Full repo artifact" \
            --path full-repo.zip
          
# # ==========================================================
# # =================  SONAR SCAN ============================
# # ==========================================================

#   sonar-scan:
#     runs-on: ubuntu-latest
#     needs: upload-artifact

#     steps:
#       - uses: actions/checkout@v4

#       - name: Sonar Scan (Java)
#         if: ${{ hashFiles(format('{0}/pom.xml', env.JAVA_DIR)) != '' }}
#         run: |
#           cd $JAVA_DIR
#           mvn sonar:sonar \
#             -Dsonar.projectKey=multi-lang-demo \
#             -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
#             -Dsonar.login=${{ secrets.SONAR_TOKEN }}

#       - name: Sonar Scan (Python/Node)
#         if: ${{ hashFiles(format('{0}/pom.xml', env.JAVA_DIR)) == '' }}
#         run: |
#           npm install -g sonar-scanner
#           sonar-scanner \
#             -Dsonar.projectKey=multi-lang-demo \
#             -Dsonar.sources=. \
#             -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
#             -Dsonar.login=${{ secrets.SONAR_TOKEN }}

# # ==========================================================
# # =================  SNYK SCAN ==========================
# # ==========================================================

#   snyk-scan:
#     runs-on: ubuntu-latest
#     needs: sonar-scan

#     steps:
#       - uses: actions/checkout@v4

#       - name: Install Snyk
#         run: npm install -g snyk

#       - name: Authenticate Snyk
#         run: snyk auth ${{ secrets.SNYK_TOKEN }}

#       - name: Snyk Test
#         run: |
#           if [ -f "$JAVA_DIR/pom.xml" ]; then
#             cd $JAVA_DIR
#             snyk test --severity-threshold=high --org=${{ secrets.SNYK_ORG_ID }}

#           elif [ -f "$PYTHON_DIR/requirements.txt" ]; then
#             cd $PYTHON_DIR
#             snyk test --severity-threshold=high --file=requirements.txt --org=${{ secrets.SNYK_ORG_ID }}

#           elif [ -f "$NODE_DIR/package.json" ]; then
#             cd $NODE_DIR
#             snyk test --severity-threshold=high --file=package.json --org=${{ secrets.SNYK_ORG_ID }}

#           else
#             echo "No supported project found"
#             exit 1
#           fi

# ==========================================================
# ================= DOCKER BUILD & PUSH ====================
# ==========================================================

  docker-build-push:
    runs-on: ubuntu-latest
    # needs: snyk-scan

    steps:
      - uses: actions/checkout@v4

      # ================= BUILD IMAGE =================
      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:$VERSION .
          docker tag $IMAGE_NAME:$VERSION $IMAGE_NAME:latest

      # ================= AWS =================
      - name: Configure AWS Credentials
        if: github.event.inputs.cloud == 'aws'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::088310115913:role/OpenID-Connect
          aws-region: us-east-1

      - name: Login to AWS ECR
        if: github.event.inputs.cloud == 'aws'
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push to AWS ECR
        if: github.event.inputs.cloud == 'aws'
        run: |
          docker tag $IMAGE_NAME:$VERSION ${{ secrets.AWS_ECR_URL }}/$ECR_REPO:$VERSION
          docker tag $IMAGE_NAME:latest ${{ secrets.AWS_ECR_URL }}/$ECR_REPO:latest
          docker push ${{ secrets.AWS_ECR_URL }}/$ECR_REPO:$VERSION
          docker push ${{ secrets.AWS_ECR_URL }}/$ECR_REPO:latest

      # ================= GCP =================
      - name: Authenticate to GCP
        if: github.event.inputs.cloud == 'gcp'
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Configure Docker for GCR
        if: github.event.inputs.cloud == 'gcp'
        run: gcloud auth configure-docker

      - name: Push to GCP
        if: github.event.inputs.cloud == 'gcp'
        run: |
          docker tag $IMAGE_NAME:$VERSION gcr.io/${{ secrets.GCP_PROJECT_ID }}/$IMAGE_NAME:$VERSION
          docker tag $IMAGE_NAME:latest gcr.io/${{ secrets.GCP_PROJECT_ID }}/$IMAGE_NAME:latest
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/$IMAGE_NAME:$VERSION
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/$IMAGE_NAME:latest

      # ================= AZURE =================
      - name: Azure Login
        if: github.event.inputs.cloud == 'azure'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Push to Azure ACR
        if: github.event.inputs.cloud == 'azure'
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}
          docker tag $IMAGE_NAME:$VERSION ${{ secrets.ACR_NAME }}.azurecr.io/$IMAGE_NAME:$VERSION
          docker tag $IMAGE_NAME:latest ${{ secrets.ACR_NAME }}.azurecr.io/$IMAGE_NAME:latest
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/$IMAGE_NAME:$VERSION
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/$IMAGE_NAME:latest
          
# ==========================================================
# ================= HELM DEPLOYMENT (CD) ===================
# ==========================================================

  deploy-helm:
    runs-on: ubuntu-latest
    needs: docker-build-push

    steps:
      - uses: actions/checkout@v4

      # Install kubectl
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      # Install Helm
      - name: Setup Helm
        uses: azure/setup-helm@v4

# ================= AWS EKS =================

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::088310115913:role/OpenID-Connect
          aws-region: us-east-1

      # Enable API authentication for EKS
      - name: Enable EKS API Authentication
        run: |
          aws eks update-cluster-config \
            --name ${{ secrets.EKS_CLUSTER }} \
            --access-config authenticationMode=API_AND_CONFIG_MAP \
            --region us-east-1 || true
      
      # Wait until the cluster update is completed
      - name: Wait for Cluster Update
        run: |
          echo "Waiting for cluster to become active..."
          aws eks wait cluster-active \
            --name ${{ secrets.EKS_CLUSTER }} \
            --region us-east-1
      
      # Create access entry for GitHub OIDC role
      - name: Grant EKS Access
        run: |
          aws eks create-access-entry \
            --cluster-name ${{ secrets.EKS_CLUSTER }} \
            --principal-arn arn:aws:iam::088310115913:role/OpenID-Connect \
            --type STANDARD \
            --region us-east-1 || true
      
          aws eks associate-access-policy \
            --cluster-name ${{ secrets.EKS_CLUSTER }} \
            --principal-arn arn:aws:iam::088310115913:role/OpenID-Connect \
            --policy-arn arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy \
            --access-scope type=cluster \
            --region us-east-1 || true
      
      # Get kubeconfig
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --name ${{ secrets.EKS_CLUSTER }} \
            --region us-east-1
      
      # Verify access
      - name: Test Cluster Access
        run: kubectl get nodes
        
      - name: Validate Helm Chart
        run: helm lint ./helm
      # Deploy application using Helm
      - name: Helm Deploy
        run: |
          helm upgrade --install multiapp ./helm \
            --set image.repository=${{ secrets.AWS_ECR_URL }}/demos/multiapp \
            --set image.tag=${{ env.VERSION }}
            
# ================= GCP GKE =================

      - name: Authenticate to GCP
        if: github.event.inputs.cloud == 'gcp'
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Get GKE Credentials
        if: github.event.inputs.cloud == 'gcp'
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} \
            --region us-central1 \
            --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Helm Deploy to GKE
        if: github.event.inputs.cloud == 'gcp'
        run: |
          helm upgrade --install multiapp ./helm \
            --set image.repository=gcr.io/${{ secrets.GCP_PROJECT_ID }}/$IMAGE_NAME \
            --set image.tag=$VERSION

# ================= AZURE AKS =================

      - name: Azure Login
        if: github.event.inputs.cloud == 'azure'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Connect to AKS
        if: github.event.inputs.cloud == 'azure'
        run: |
          az aks get-credentials \
            --resource-group ${{ secrets.AKS_RG }} \
            --name ${{ secrets.AKS_CLUSTER }}

      - name: Helm Deploy to AKS
        if: github.event.inputs.cloud == 'azure'
        run: |
          helm upgrade --install multiapp ./helm \
            --set image.repository=${{ secrets.ACR_NAME }}.azurecr.io/$IMAGE_NAME \
            --set image.tag=$VERSION
